"~/" = [
  ".tmux.conf",
  ".tmux-line.conf",
  ".dir_colors",
  ".doom.d",
  ".zshrc",
  "aliases.sh",
]
"~/.config/fish/" = ["config.fish", "aliases.fish"]
"~/.config/nvim/" = ["init.lua", "lua"]
"~/.config/kitty/" = ["kitty.conf", "kitty-theme.conf"]
"~/.config/mise/" = [{ src = "mise.toml", dst = "config.toml" }]
"~/.tmux/plugins" = ["tpm"]
