require("config.lazy")
vim.cmd('colorscheme onenord')
require("config.lsp")
require("config.oil")
require("config.lualine")
require("config.telescope")
require("config.completion")
require("config.keybindings")
